name: Deploy Backend to Render

on:
  push:
    branches: [main]  # Trigger on push to the main branch
  pull_request:
    types: [closed]   # Trigger when a pull request is closed (merged or closed without merging)
    branches: [main]  # Only for pull requests targeting the main branch

jobs:
  deploy-backend:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment

    steps:
      - name: Trigger Backend Deployment
        if: github.ref == 'refs/heads/main' || (github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main')
        env:
          DEPLOY_HOOK_URL: ${{ secrets.RENDER_BACKEND_DEPLOY_HOOK_URL }}  # Use the backend deploy hook secret
        run: |
          curl -X POST "$DEPLOY_HOOK_URL"